### ISSUE TITLE
Documentation on bare minimum set up in Stripe for use of this starter

### ISSUE THREAD

**Issue by stcalica** [brxck/gatsby-starter-stripe#12]
## Expected Behavior
I expect to add my stripe keys and follow the instructions to get a basic working demo or starter. 

## Current Behavior
Able to add my stripe keys and get an okay build but still some issues on setup. 

## Possible Solution
Create some documentation on the bare minimum needed to set this up. Such as a sku with image, price and etc.

**Comment by brxck** [comment]
Hey, thanks for checking out the starter. The [query in the ProductsProvider](https://github.com/brxck/gatsby-starter-stripe/blob/7eca83b18106d9ebe8304efa5a8c6991bcc33412/src/components/ProductsProvider.js#L111) lists the properties the starter will try and find on your Stripe skus. Is this what you are looking for? I can add this to the documentation.

**Comment by stcalica** [comment]
Yeah, that's a good space to see what's the bare minimum needed but might want to add some more explicit documentation if possible. Would have made it easier to try out right away
