### ISSUE TITLE
The orders API and consequently the SKU endpoint has been deprecated

### ISSUE THREAD

**Issue by coquizen** [brxck/gatsby-starter-stripe#26]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by brxck** [comment]
Yes the Orders API is deprecated; however, [Stripe has no apparent plans to remove Skus](https://twitter.com/stripe/status/1264940450718330880), and migrating to prices would mean losing the ability to manage a limited inventory without the use of an external service.
