### ISSUE TITLE
Cannot query field "allStripeSku" on type "Query". –– GraphQL can't find allStripeSku

### ISSUE THREAD

**Issue by supnim** [brxck/gatsby-starter-stripe#27]
Hey,  I'm relatively new to this so forgive me if this is something obvious.

## Expected Behavior

Expecting the page to load with products that I've created on Stripe, this work when I manually input e.g one button like on this tutorial (https://www.gatsbyjs.org/tutorial/ecommerce-tutorial/#example-1-one-button) but when I try to query it does not.
 
ive changed evn.emaple to env with test passwords and added products in stripe but still no luck

## Current Behavior
graphql does't recognise allStripeSku and throws this error 
```
success open and validate gatsby-configs - 0.016s
success load plugins - 0.773s
success onPreInit - 0.010s
success initialize cache - 0.017s
success copy gatsby files - 0.037s
success onPreBootstrap - 0.006s
success createSchemaCustomization - 0.003s
error (node:9521) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
success source and transform nodes - 3.220s
success building schema - 0.211s
error There was an error in your GraphQL query:

Cannot query field "allStripeSku" on type "Query".

If you don't expect "allStripeSku" to exist on the type "Query" it is most likely a typo.
However, if you expect "allStripeSku" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allStripeSku" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
error Cannot query field "allStripeSku" on type "Query". Did you mean "allSite" or "allStripeProduct"?


  GraphQLError: Cannot query field "allStripeSku" on type "Query". Did you mean   "allSite" or "allStripeProduct"?
  
  - graphql-runner.js:95 GraphQLRunner.validate
    [brite.london]/[gatsby]/dist/query/graphql-runner.js:95:44
  
  - graphql-runner.js:161 GraphQLRunner.query
    [brite.london]/[gatsby]/dist/query/graphql-runner.js:161:25
  
  - create-graphql-runner.js:33 
    [brite.london]/[gatsby]/dist/bootstrap/create-graphql-runner.js:33:37
  
  - gatsby-node.js:21 Object.exports.createPages
    /Users/nimesh/Desktop/brite.london/gatsby-node.js:21:10
  
  - api-runner-node.js:256 runAPI
    [brite.london]/[gatsby]/dist/utils/api-runner-node.js:256:37
  
  - api-runner-node.js:375 Promise.catch.decorateEvent.pluginName
    [brite.london]/[gatsby]/dist/utils/api-runner-node.js:375:15
  
  - debuggability.js:384 Promise._execute
    [brite.london]/[bluebird]/js/release/debuggability.js:384:9
  
  - promise.js:518 Promise._resolveFromExecutor
    [brite.london]/[bluebird]/js/release/promise.js:518:18
  
  - promise.js:103 new Promise
    [brite.london]/[bluebird]/js/release/promise.js:103:10
  
  - api-runner-node.js:374 
    [brite.london]/[gatsby]/dist/utils/api-runner-node.js:374:12
  
  - util.js:16 tryCatcher
    [brite.london]/[bluebird]/js/release/util.js:16:23
  

not finished createPages - 0.043s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-stripe@0.2.0 start: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-stripe@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nimesh/.npm/_logs/2020-07-24T14_33_17_789Z-debug.log
◈ "npm run start" exited with code 1. Shutting down Netlify Dev server
```
Any help would be greatly appreciated as I've been going in circles for the last two days trying to figure it out :)

**Comment by brxck** [comment]
It sounds like you don't have any [Skus](https://stripe.com/docs/api/skus) attached to your Products? 

I'm guessing this because the new Products section of the Stripe dashboard allows you to add Prices to Products, but not Skus unfortunately. The ability to create Skus in the dashboard is hidden away in the Orders section.

**Comment by supnim** [comment]
ive tried adding sku via CLI, which throws this error:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/38427203/88821405-8a24a100-d1ba-11ea-8dc9-488379964670.png">

and weirdly i dont have a orders sections:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/38427203/88821728-ec7da180-d1ba-11ea-851f-333a9a1f962e.png">

I appreciate troubleshooting isn't your job but I've gone in cycles about 2weeks now and any help would be swell :)

p.s im trying to sell tee shirts online

**Comment by brxck** [comment]
No problem! Products with Skus need to have the `type` property set to `good`. You'll need to update that Product first or add another. 

I'll see about adding something to the README since we need something other than the default behavior of the dashboard. 

I've also used this to sell t-shirts before!

**Comment by hoangausway** [comment]
Hi,
The Order/SKU API was deprecated and the stripe dashboard doesn't allow you to enter SKU anymore.
It would be great if @brxck could upgrade this starter to reflect the changes.

**Comment by brxck** [comment]
Yep the Orders API is deprecated, though it's still functional, as is the starter. Once you have added products using Orders API, it becomes visible in the Dashboard. 

I probably won't have time to migrate this starter in the near future. Accepting any PRs. 

@supnim, please let me know if you need any other help with the starter. I think we've covered your problem here so I'm going to close this issue.

**Comment by supnim** [comment]
fair enough, ill try that out - cheers for all the help :)

**Comment by yansusanto** [comment]
@supnim Sorry that I have to reopen this thread. I'm just wondering if you manage to find a fix for this. Thanks in advance!

**Comment by michalien** [comment]
Stripe deprecated skus in their api. A new stripe account or an existing one that you have just added products to have no dashboard support for skus. Neither this starter nor the gatsby-source-stripe plugin yet support that change. Although the work to update both starter and source appears to be done some time ago, we are all still waiting for those changes to be merged. If you check the @brxck PR you can see the changes in the codebase and apply them yourself.

**Comment by supnim** [comment]
@yansusanto that's okay, I couldn't figure it out and abandoned it :( so I'm no help to you bro
