### ISSUE TITLE
Example for a Subscription Item

### ISSUE THREAD

**Issue by buzzguy** [brxck/gatsby-starter-stripe#3]
This is working well with products with sku's, but could you add an example for a subscription item that you can add to a cart and order?

**Comment by brxck** [comment]
Hey thanks for checking out the starter! I'll look into this, but I haven't yet made use of subscriptions myself. 

My feeling is that no matter what, there would be a fair amount of work left for the developer to do — the managing of subscriptions (ex. changing plans, updating payments, cancelling) would fall outside the scope of this starter, which aims to be pretty minimal.

In any case, I hope that the providers and functions already in the starter provide good examples/inspiration to build on the specific functionality you need.

I'll update this issue with any decisions or progress 👍

**Comment by buzzguy** [comment]
That’s true, the context product provider is already a good blueprint
