### ISSUE TITLE
Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js

### ISSUE THREAD

**Issue by coelmay** [brxck/gatsby-starter-stripe#35]
Hi @brxck,

After running `netlify dev` and reloading the browser I get

**One unhandled runtime error found in your files. See the list below to fix it:**
Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77
The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

./.cache/gatsby-browser-entry.js:77
````
  75 |     return context[query].data
  76 |   } else {
> 77 |     throw new Error(
     |          ^
  78 |       `The result of this StaticQuery could not be fetched.\n\n` +
  79 |         `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
  80 |         `please open an issue in https://github.com/gatsbyjs/gatsby/issues
````
It says it is a Gatsby issue, however as I do not know enough about either this starter or Gatsby generally, I thought I would post here first.

Screengrab of error message:
<img width="1265" alt="Screen Shot 2021-05-08 at 2 25 28 pm" src="https://user-images.githubusercontent.com/82788995/117526540-442e2080-b009-11eb-81b6-e2b3662d70e0.png">

**Comment by brxck** [comment]
This isn't something I've encountered before, and unfortunately there's not a lot to go on here.

Deleting Gatsby's `.cache/` can sometimes resolve Gatsby errors. I might also try removing `node_modules/` and attempting a fresh npm install. 

There looks to be discussion of this error in the Gatsby repo: https://github.com/gatsbyjs/gatsby/issues/24902

Best of luck! Please let me know if more info turns up or if it turns out to be related to the starter.

**Comment by coelmay** [comment]
Thanks @brxck 
I did try deleting `.cache` without success. I shall read through thread you mentioned and let you know the result.

**Comment by coelmay** [comment]
Followed the "fix" mentioned in https://github.com/gatsbyjs/gatsby/issues/24902#issuecomment-822968958 and after a couple of hiccups, all seems working.

**Comment by DOSputin** [comment]
> Followed the "fix" mentioned in [gatsbyjs/gatsby#24902 (comment)](https://github.com/gatsbyjs/gatsby/issues/24902#issuecomment-822968958) and after a couple of hiccups, all seems working.

I'm having same issue. 
That discussion you linked is a longwinded one.  
I removed `node_modules` reinstalled and cleaned cache.  No joy.
Would you mind detailing what hiccups were to get past this booger?

**Comment by coelmay** [comment]
@DOSputin The comment I linked to is "the fix" I followed. What more do you need detailed?

**Comment by DOSputin** [comment]
> @DOSputin The comment I linked to is "the fix" I followed. What more do you need detailed?

Your comment seemed to elude to a few other steps that you took, a la; hiccups?  

> Followed the "fix" mentioned in [gatsbyjs/gatsby#24902 (comment)] and after a couple of hiccups, all seems working.

**Comment by coelmay** [comment]
> Your comment seemed to elude to a few other steps that you took, a la; hiccups?

Unfortunately I do not remember what those hiccups were.

**Comment by DOSputin** [comment]
been mashing on this for hours now.  still can't get past this nasty runtime booger.  
Show stopper.
