### ISSUE TITLE
Server Errors (500) POSTing to Stripe

### ISSUE THREAD

**Issue by zedd45** [brxck/gatsby-starter-stripe#7]
I have encountered server errors when using a test account locally, as well as on the the [demo site](https://gatsby-starter-stripe.netlify.com/buy/msr-hubba-hubba-nx-2).  This occurs after entering a valid test CC number from [the stripe docs](https://stripe.com/docs/testing#cards) and submitting the form. 

## Expected Behavior

Successful transaction should process and ([potentially redirect?](https://github.com/brxck/gatsby-starter-stripe/blob/e7782fe8586120d9de200de1c9f997f4353c5327/src/components/Checkout.js#L45)) send a `200`.

## Current Behavior

The server responds with a 500, and sends an `alert` message stating 
> Unexpected token F in JSON at position 0

The response body appears to be empty, and the following error is emitted in the server logs: 

```
Error during invocation:  TypeError: Cannot read property 'id' of undefined
    at Object.e.exports.handler (/{Project}/functions/orderCreate.js:1:61150)
    at process._tickCallback (internal/process/next_tick.js:68:7)
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at callback (/{Project}/node_modules/netlify-lambda/lib/serve.js:37:16)
    at p (/{Project}/functions/orderCreate.js:1:61125)
    at n.orders.create (/{Project}/functions/orderCreate.js:1:60996)
    at Timeout._onTimeout (/{Project}/functions/orderCreate.js:1:9248)
```
 

## Possible Solution

I have tried upgrading `gatsby-stripe-starter` to `v3.0.x` per comments in [issue 2](https://github.com/brxck/gatsby-starter-stripe/issues/2#issuecomment-487730613), but this did not solve the problem.

I am attempting to put some guards around `order.id`. It's hard to make sense of the line numbers, since the stack trace is claiming line 1 contains the error.

I will also try to remove the `headers` where [the response object is built](https://github.com/brxck/gatsby-starter-stripe/blob/e7782fe8586120d9de200de1c9f997f4353c5327/src/functions/orderCreate.js#L36-L38) and see if this helps.  I will report back after I try this.

## Steps to Reproduce (for bugs)

1. Navigate to https://gatsby-starter-stripe.netlify.com/buy/msr-hubba-hubba-nx-2 (or similar URL locally)
1. Click "add item to cart"
1. Click "checkout for $xxx" 
1. fill out the payment form with test data
1. submit the payment
1. Observe an `alert` dialog with the aforementioned error message.

## Context

This happens for me locally as well as on the demo.  I am trying to handle the success condition to process emails and confirmation screen, but I'm unable to get there.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

OS: OSX 'Mojave' `10.14.5`
Node: `v10.15.3`
Chrome: `74.0.3729.169 (Official Build) (64-bit)` Desktop

**Comment by zedd45** [comment]
It looks like the array destructuring order for quantity and skuId might be reversed / and or embedded in another array (see screenshot). I tried modifying that, but the Stripe API rejects the request saying it's an invalid string.
```
 const items = Object.entries(cart).map(([, cartContents]) => {
      const [skuId, quantity] = cartContents;
      return {
        type: 'sku',
        parent: skuId,
        quantity,
      };
    });
```

![SkuId   Quantity reversed?](https://user-images.githubusercontent.com/546437/59565713-c6338b80-9024-11e9-922d-95c0e5b0c63a.png)

**Comment by brxck** [comment]
Thanks for reporting this and thank you for the detailed issue! This was, in part, due to the things you pointed out. The latest commit should fix this.

**Comment by zedd45** [comment]
I submitted a PR to stringify the body for the response.  I was receiving an error from the netlify lib's `serve.js`.

**Comment by DOSputin** [comment]
![image](https://user-images.githubusercontent.com/32726022/62003705-fb290880-b0cf-11e9-9928-c2eaa44ce64d.png)

Seems like this is still an issue.  This is on the currently deployed example demo.

**Comment by brxck** [comment]
Hey, thanks for checking out the starter! I believe this was actually fixed above; however, the deployed demo is an old build which still has this bug. I've not been able to redeploy a new demo as for some reason (???) gatsby-source-stripe is now failing to pull some images on rebuild, though nothing there has changed and I have not been able to determine why. The code in the repo does not have this issue.

**Comment by zedd45** [comment]
We didn't change any of the dependencies lately, correct? I think I upgraded one of my local dependencies, but I thought I rolled it back.  

It looks like the version of `gatsby-source-stripe` was updated with bc17bfb288d29448be1e0e48d505b0b008a5e14f, but I wonder if that is related? Locally I tried upgrading to `3.x.x`, but it looks like I downgraded it back to `2.x.x` locally for some reason. 
```
"gatsby-source-stripe": "2.x.x",
```

**Comment by brxck** [comment]
@zedd45 [Yesterday's commit](https://github.com/brxck/gatsby-starter-stripe/commit/7eca83b18106d9ebe8304efa5a8c6991bcc33412) upgraded gatsby-source-stripe to 3.0.2, and many others were also upgraded due to security vulnerabilities. 

As for the problem I described above, I've filed an [issue](https://github.com/njosefbeck/gatsby-source-stripe/issues/42) at gatsby-source-stripe.
